import { useGetUserPostQuery } from "@/rtk/service";
import styles from "@/styles/Home.module.css";
import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  const { data, isLoading } = useGetUserPostQuery(1);

  return (
    <>
      {isLoading || !data ? (
        <div>Loading...</div>
      ) : (
        <div className={styles.container}>
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>

          <main className={styles.main}>
            <p>{data.title}</p>
            <p>{data.body}</p>
          </main>
        </div>
      )}
    </>
  );
};

export default Home;
